name: Publish Docker

on:
  push:
    branches:
    - master

env:
  REGISTRY: ghcr.io
  NAMESPACE: ${{ github.repository_owner }}
  IMAGE_NAME: ${{ github.repository }}
  VERSION: '4.1.2'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    permissions:
      contents: 'write'
      packages: 'write'
      id-token: 'write'

    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - id: get-tag
      name: Compute image tag as "x.y.z-sha7"
      run: echo "tag=$VERSION-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - id: docker-push-tagged
      name: Tag Docker image and push to Google Artifact Registry
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.get-tag.outputs.tag }}

    - name: Create tag
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: "refs/tags/${{ steps.get-tag.outputs.tag }}",
            sha: context.sha
          })


